services:
  omniscan:
    restart: unless-stopped 
    container_name: omniscan 
    image: ghcr.io/drondeseries/omniscan:latest
    hostname: omniscan 
    ports:
      - 8085:8000
    environment:
      - TZ=${TZ:-UTC}
      - OMNISCAN_BOOTSTRAP_TOKEN=${OMNISCAN_BOOTSTRAP_TOKEN:-}
    volumes: 
      - /media/docker/data/omniscan:/app/config
      - /etc/localtime:/etc/localtime:ro
      - /mnt:/mnt:ro,rslave
      - /media:/media:ro,rslave
    networks:
      - pangolin

networks:
  pangolin:
    external: true